version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    network_mode: "host"
  backend:
    build:
      context: ./backend
    network_mode: "host"
