name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Docker Hub Login
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USER }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Docker Hub Push
      #  env:
      # Docker hub repository name
      #    REPO: react-portfolio
      #  run: |
      #    docker build -t $REPO -f ./client/Dockerfile.local ./client/.
      #    docker tag $REPO:latest ${{ secrets.DOCKER_USER }}/$REPO:latest
      #    docker push ${{ secrets.DOCKER_USER }}/$REPO

      #- name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: ap-south-1

      #- name: Pull docker image from Docker Hub
      #  env:
      # Docker hub repository name
      #    REPO: react-portfolio
      #  run: |
      # docker login
      # docker pull ${{ secrets.DOCKER_USER }}/$REPO
      # docker stop portfolio_frontend
      # docker rm portfolio_frontend
      # docker run --detach --name portfolio_frontend -p 3000:3000 ${{ secrets.DOCKER_USER }}/$REPO

      - name: Docker pull & Run from Hub
        env:
          REPO: react-portfolio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker login
            docker pull ${{ secrets.DOCKER_USER }}/$REPO
            docker stop portfolio_frontend
            docker rm portfolio_frontend
            docker run --detach --name portfolio_frontend -p 3000:3000 ${{ secrets.DOCKER_USER }}/$REPO
            
            
